targets:
    $default:
        builders:
            i18n_builder:
                enabled: true
                generate_for:
                    - lib/**.dart
                options:
                    translations_dir: "assets/translations"
                    base_locale: "en-US"

builders:
    i18n_builder:
        import: "package:i18n_builder/i18n_builder.dart"
        builder_factories: ["i18nBuilder"]
        build_extensions:
            ".dart": [".i18n_dummy"]
        auto_apply: root_package
        build_to: cache
