targets:
    $default:
        builders:
            i18n_builder:
                enabled: true

builders:
    i18n_builder:
        target: ":i18n_builder"
        import: "package:i18n_builder/i18n_builder.dart"
        builder_factories: ["i18nBuilder"]
        build_extensions: {} # No file outputs
        auto_apply: root_package
        build_to: source
